<?php

namespace Database\Seeders;

use App\Models\GameCategory;
use Illuminate\Database\Seeder;
use App\Enums\GameCategoryStatus;
// use Faker\Factory as Faker;
class GameCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // GameCategory::factory(100)->create();
       

        GameCategory::insert([
            [
                'sort_order' => 1,
                'name' => 'Robux',
                'slug' => 'robux',
                'description' => 'Robux',
                'meta_title' => 'Robux',
                'meta_description' => 'Robux',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 2,
                'name' => 'Steal A Brainrot',
                'slug' => 'steal-a-brainrot',
                'description' => 'Steal A Brainrot',
                'meta_title' => 'Steal A Brainrot',
                'meta_description' => 'Steal A Brainrot',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 3,
                'name' => 'Grow A Garden',
                'slug' => 'grow-a-garden',
                'description' => 'Steal A Brainrot',
                'meta_title' => 'Grow A Garden',
                'meta_description' => 'Grow A Garden',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 4,
                'name' => 'Hunty Zombie',
                'slug' => 'hunty-zombie',
                'description' => 'Hunty Zombiet',
                'meta_title' => 'Hunty Zombie',
                'meta_description' => 'Hunty Zombie',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 5,
                'name' => '99 Nights In The Forest',
                'slug' => '99-nights-in-the-forest',
                'description' => '99 Nights In The Forestt',
                'meta_title' => '99 Nights In The Forest',
                'meta_description' => '99 Nights In The Forest',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 6,
                'name' => 'Prospecting',
                'slug' => 'prospecting',
                'description' => 'Prospectingt',
                'meta_title' => 'Prospecting',
                'meta_description' => 'Prospecting',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 7,
                'name' => 'All Star Tower Defense X',
                'slug' => 'all-star-tower-defense-x',
                'description' => 'All Star Tower Defense X',
                'meta_title' => 'All Star Tower Defense X',
                'meta_description' => 'All Star Tower Defense X',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 8,
                'name' => 'Ink Game',
                'slug' => 'ink-game',
                'description' => 'Ink Game',
                'meta_title' => 'Ink Game',
                'meta_description' => 'Ink Game',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 9,
                'name' => 'Garden Tower Defense',
                'slug' => 'garden-tower-defense',
                'description' => 'Garden Tower Defense',
                'meta_title' => 'Garden Tower Defense',
                'meta_description' => 'Garden Tower Defense',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 10,
                'name' => 'Bubble Gum Simulator',
                'slug' => 'bubble-gum-simulator',
                'description' => 'Bubble Gum Simulator',
                'meta_title' => 'Bubble Gum Simulator',
                'meta_description' => 'Bubble Gum Simulator',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 11,
                'name' => 'Dead Rails',
                'slug' => 'dead-rails',
                'description' => 'Dead Rails',
                'meta_title' => 'Dead Rails',
                'meta_description' => 'Dead Rails',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 12,
                'name' => 'TYPE./ ISOUL',
                'slug' => 'type-isoul',
                'description' => 'TYPE./ ISOUL',
                'meta_title' => 'TYPE./ ISOUL',
                'meta_description' => 'TYPE./ ISOUL',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 13,
                'name' => 'Hypershot',
                'slug' => 'hypershot',
                'description' => 'Hypershot',
                'meta_title' => 'Hypershot',
                'meta_description' => 'Hypershot',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 14,
                'name' => 'Build A Zoo',
                'slug' => 'build-a-zoo',
                'description' => 'Build A Zoo',
                'meta_title' => 'Build A Zoo',
                'meta_description' => 'Build A Zoo',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 15,
                'name' => 'Gems',
                'slug' => 'gems',
                'description' => 'Gems',
                'meta_title' => 'Gems',
                'meta_description' => 'Gems',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 16,
                'name' => 'Rivals',
                'slug' => 'rivals',
                'description' => 'Rivals',
                'meta_title' => 'Rivals',
                'meta_description' => 'Rivals',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 17,
                'name' => 'MM2',
                'slug' => 'mm2',
                'description' => 'MM2',
                'meta_title' => 'MM2',
                'meta_description' => 'MM2',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 18,
                'name' => 'Blox Fruit',
                'slug' => 'blox-fruit',
                'description' => 'Blox Fruit',
                'meta_title' => 'Blox Fruit',
                'meta_description' => 'Blox Fruit',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 19,
                'name' => 'Pet Simulator 99',
                'slug' => 'pet-simulator-99',
                'description' => 'Pet Simulator 99',
                'meta_title' => 'Pet Simulator 99',
                'meta_description' => 'Pet Simulator 99',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 20,
                'name' => 'Spin',
                'slug' => 'spin',
                'description' => 'Spin',
                'meta_title' => 'Spin',
                'meta_description' => 'Spin',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 21,
                'name' => 'Adopt Me',
                'slug' => 'adopt-me',
                'description' => 'Adopt Me',
                'meta_title' => 'Adopt Me',
                'meta_description' => 'Adopt Me',
                'icon' => '',
                'is_featured' => 1,
                'status' => GameCategoryStatus::ACTIVE->value,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
