<?php

namespace Database\Seeders;

use App\Models\Game;
use App\Enums\GameStatus;
use App\Models\Admin;
use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dummyLogo = 'https://dummyimage.com/600x600/cccccc/cccccc';

        $games = [
            [
                'sort_order' => 1,
                'name' => 'EA Sports FC Coins',
                'slug' => 'ea-sports-fc-coins',
                'description' => 'EA Sports FC Coins',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'EA Sports FC Coins',
                'meta_description' => 'EA Sports FC Coins',
                'meta_keywords' => 'EA Sports FC Coins',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 2,
                'name' => 'Albion Online Silver',
                'slug' => 'albion-online-silver',
                'description' => 'Albion Online Silver',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Albion Online Silver',
                'meta_description' => 'Albion Online Silver',
                'meta_keywords' => 'Albion Online Silver',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 3,
                'name' => 'Animal Crossing: New Horizons Bells',
                'slug' => 'animal-crossing-new-horizons-bells',
                'description' => 'Animal Crossing: New Horizons Bells',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Animal Crossing: New Horizons Bells',
                'meta_description' => 'Animal Crossing: New Horizons Bells',
                'meta_keywords' => 'Animal Crossing: New Horizons Bells',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 4,
                'name' => 'Black Desert Online Silver',
                'slug' => 'black-desert-online-silver',
                'description' => 'Black Desert Online Silver',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Black Desert Online Silver',
                'meta_description' => 'Black Desert Online Silver',
                'meta_keywords' => 'Black Desert Online Silver',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 5,
                'name' => 'Blade & Soul NEO Divine Gems',
                'slug' => 'blade-soul-neo-divine-gems',
                'description' => 'Blade & Soul NEO Divine Gems',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Blade & Soul NEO Divine Gems',
                'meta_description' => 'Blade & Soul NEO Divine Gems',
                'meta_keywords' => 'Blade & Soul NEO Divine Gems',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 6,
                'name' => 'Blade Ball Tokens',
                'slug' => 'blade-ball-tokens',
                'description' => 'Blade Ball Tokens',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Blade Ball Tokens',
                'meta_description' => 'Blade Ball Tokens',
                'meta_keywords' => 'Blade Ball Tokens',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 7,
                'name' => 'New World Coins',
                'slug' => 'new-world-coins',
                'description' => 'New World Coins',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'New World Coins',
                'meta_description' => 'New World Coins',
                'meta_keywords' => 'New World Coins',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 8,
                'name' => 'Path of Exile 2 Currency',
                'slug' => 'path-of-exile-2-currency',
                'description' => 'Path of Exile 2 Currency',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Path of Exile 2 Currency',
                'meta_description' => 'Path of Exile 2 Currency',
                'meta_keywords' => 'Path of Exile 2 Currency',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 9,
                'name' => 'Throne and Liberty Lucent',
                'slug' => 'throne-and-liberty-lucent',
                'description' => 'Throne and Liberty Lucent',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Throne and Liberty Lucent',
                'meta_description' => 'Throne and Liberty Lucent',
                'meta_keywords' => 'Throne and Liberty Lucent',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 10,
                'name' => 'Worldforge Legends',
                'slug' => 'worldforge-legends',
                'description' => 'Worldforge Legends',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Worldforge Legends',
                'meta_description' => 'Worldforge Legends',
                'meta_keywords' => 'Worldforge Legends',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 11,
                'name' => 'Exilecon Official Trailer',
                'slug' => 'exilecon-official-trailer',
                'description' => 'Exilecon Official Trailer',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Exilecon Official Trailer',
                'meta_description' => 'Exilecon Official Trailer',
                'meta_keywords' => 'Exilecon Official Trailer',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 12,
                'name' => 'Echoes of the Terra',
                'slug' => 'echoes-of-the-terra',
                'description' => 'Echoes of the Terra',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Echoes of the Terra',
                'meta_description' => 'Echoes of the Terra',
                'meta_keywords' => 'Echoes of the Terra',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 13,
                'name' => 'Epochs of Gaia',
                'slug' => 'epochs-of-gaia',
                'description' => 'Epochs of Gaia',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Epochs of Gaia',
                'meta_description' => 'Epochs of Gaia',
                'meta_keywords' => 'Epochs of Gaia',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 14,
                'name' => 'Titan Realms',
                'slug' => 'titan-realms',
                'description' => 'Titan Realms',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Titan Realms',
                'meta_description' => 'Titan Realms',
                'meta_keywords' => 'Titan Realms',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 15,
                'name' => 'Kingdoms Across Skies',
                'slug' => 'kingdoms-across-skies',
                'description' => 'Kingdoms Across Skies',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Kingdoms Across Skies',
                'meta_description' => 'Kingdoms Across Skies',
                'meta_keywords' => 'Kingdoms Across Skies',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 16,
                'name' => 'Realmwalker: New Dawn',
                'slug' => 'realmwalker-new-dawn',
                'description' => 'Realmwalker: New Dawn',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Realmwalker: New Dawn',
                'meta_description' => 'Realmwalker: New Dawn',
                'meta_keywords' => 'Realmwalker: New Dawn',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 17,
                'name' => 'RuneScape 3 Gold',
                'slug' => 'runescape-3-gold',
                'description' => 'RuneScape 3 Gold',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'RuneScape 3 Gold',
                'meta_description' => 'RuneScape 3 Gold',
                'meta_keywords' => 'RuneScape 3 Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 18,
                'name' => 'Lost Ark Gold',
                'slug' => 'lost-ark-gold',
                'description' => 'Lost Ark Gold',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Lost Ark Gold',
                'meta_description' => 'Lost Ark Gold',
                'meta_keywords' => 'Lost Ark Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 19,
                'name' => 'Old School RuneScape Gold',
                'slug' => 'old-school-runescape-gold',
                'description' => 'Old School RuneScape Gold',
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Old School RuneScape Gold',
                'meta_description' => 'Old School RuneScape Gold',
                'meta_keywords' => 'Old School RuneScape Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Add same dummy logo to all
        foreach ($games as &$game) {
            $game['logo'] = $dummyLogo;
        }

        Game::insert($games);
    }
}
