<?php

namespace Database\Seeders;

use App\Models\Game;
use App\Enums\GameStatus;
use App\Models\Admin;
use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $dummyLogo = 'https://dummyimage.com/600x600/cccccc/cccccc';

        // $games = [
        //     [
        //         'sort_order' => 1,
        //         'name' => 'EA Sports FC Coins',
        //         'slug' => 'ea-sports-fc-coins',
        //         'description' => 'EA Sports FC Coins',
        //         'logo' => asset('assets/images/games_images/header.jpg'),
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'EA Sports FC Coins',
        //         'meta_description' => 'EA Sports FC Coins',
        //         'meta_keywords' => 'EA Sports FC Coins',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 2,
        //         'name' => 'Albion Online Silver',
        //         'slug' => 'albion-online-silver',
        //         'logo' => asset("assets/images/games_images/albion-online-1759420065208.webp"),
        //         'description' => 'Albion Online Silver',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Albion Online Silver',
        //         'meta_description' => 'Albion Online Silver',
        //         'meta_keywords' => 'Albion Online Silver',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 3,
        //         'name' => 'Animal Crossing: New Horizons Bells',
        //         'slug' => 'animal-crossing-new-horizons-bells',
        //         'logo' => asset("assets/images/games_images/images.jpg"),
        //         'description' => 'Animal Crossing: New Horizons Bells',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Animal Crossing: New Horizons Bells',
        //         'meta_description' => 'Animal Crossing: New Horizons Bells',
        //         'meta_keywords' => 'Animal Crossing: New Horizons Bells',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 4,
        //         'name' => 'Black Desert Online Silver',
        //         'slug' => 'black-desert-online-silver',
        //         'logo' => asset("assets/images/games_images/header.jpg"),
        //         'description' => 'Black Desert Online Silver',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Black Desert Online Silver',
        //         'meta_description' => 'Black Desert Online Silver',
        //         'meta_keywords' => 'Black Desert Online Silver',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 5,
        //         'name' => 'Blade & Soul NEO Divine Gems',
        //         'slug' => 'blade-soul-neo-divine-gems',
        //         'logo' => asset("assets/images/games_images/1971ab43ca8-d49b0e9d-54a7-43d5-a0e7-4c64e9b8d735.jpg"),
        //         'description' => 'Blade & Soul NEO Divine Gems',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Blade & Soul NEO Divine Gems',
        //         'meta_description' => 'Blade & Soul NEO Divine Gems',
        //         'meta_keywords' => 'Blade & Soul NEO Divine Gems',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 6,
        //         'name' => 'Blade Ball Tokens',
        //         'slug' => 'blade-ball-tokens',
        //         'logo' => asset("assets/images/games_images/images.png"),
        //         'description' => 'Blade Ball Tokens',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Blade Ball Tokens',
        //         'meta_description' => 'Blade Ball Tokens',
        //         'meta_keywords' => 'Blade Ball Tokens',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 7,
        //         'name' => 'New World Coins',
        //         'slug' => 'new-world-coins',
        //         'logo' => asset("assets/images/games_images/images (1).jpg"),
        //         'description' => 'New World Coins',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'New World Coins',
        //         'meta_description' => 'New World Coins',
        //         'meta_keywords' => 'New World Coins',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 8,
        //         'name' => 'Path of Exile 2 Currency',
        //         'slug' => 'path-of-exile-2-currency',
        //         'logo' => asset("assets/images/games_images/poe-2-trading-guide-small-700x394.webp"),
        //         'description' => 'Path of Exile 2 Currency',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Path of Exile 2 Currency',
        //         'meta_description' => 'Path of Exile 2 Currency',
        //         'meta_keywords' => 'Path of Exile 2 Currency',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 9,
        //         'name' => 'Throne and Liberty Lucent',
        //         'slug' => 'throne-and-liberty-lucent',
        //         'logo' => asset("assets/images/games_images/images (2).jpg"),
        //         'description' => 'Throne and Liberty Lucent',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Throne and Liberty Lucent',
        //         'meta_description' => 'Throne and Liberty Lucent',
        //         'meta_keywords' => 'Throne and Liberty Lucent',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 10,
        //         'name' => 'Worldforge Legends',
        //         'slug' => 'worldforge-legends',
        //         'logo' => asset("assets/images/games_images/4d6f48c6f7bb2deeb6c237528d5331f4.jpg"),
        //         'description' => 'Worldforge Legends',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Worldforge Legends',
        //         'meta_description' => 'Worldforge Legends',
        //         'meta_keywords' => 'Worldforge Legends',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 11,
        //         'name' => 'Exilecon Official Trailer',
        //         'slug' => 'exilecon-official-trailer',
        //         'logo' => asset("assets/images/games_images/mqdefault.jpg"),
        //         'description' => 'Exilecon Official Trailer',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Exilecon Official Trailer',
        //         'meta_description' => 'Exilecon Official Trailer',
        //         'meta_keywords' => 'Exilecon Official Trailer',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 12,
        //         'name' => 'Echoes of the Terra',
        //         'slug' => 'echoes-of-the-terra',
        //         'logo' => asset("assets/images/games_images/Logo.webp"),
        //         'description' => 'Echoes of the Terra',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Echoes of the Terra',
        //         'meta_description' => 'Echoes of the Terra',
        //         'meta_keywords' => 'Echoes of the Terra',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 13,
        //         'name' => 'Epochs of Gaia',
        //         'slug' => 'epochs-of-gaia',
        //         'logo' => asset("assets/images/games_images/5834317.webp"),
        //         'description' => 'Epochs of Gaia',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Epochs of Gaia',
        //         'meta_description' => 'Epochs of Gaia',
        //         'meta_keywords' => 'Epochs of Gaia',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 14,
        //         'name' => 'Titan Realms',
        //         'slug' => 'titan-realms',
        //         'logo' => asset("assets/images/games_images/bg1.webp"),
        //         'description' => 'Titan Realms',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Titan Realms',
        //         'meta_description' => 'Titan Realms',
        //         'meta_keywords' => 'Titan Realms',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 15,
        //         'name' => 'Kingdoms Across Skies',
        //         'slug' => 'kingdoms-across-skies',
        //         'logo' => asset("assets/images/games_images/55a6901f06ff49aba4319ab8a50a381c78c45675.png"),
        //         'description' => 'Kingdoms Across Skies',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Kingdoms Across Skies',
        //         'meta_description' => 'Kingdoms Across Skies',
        //         'meta_keywords' => 'Kingdoms Across Skies',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 16,
        //         'name' => 'Realmwalker: New Dawn',
        //         'slug' => 'realmwalker-new-dawn',
        //         'logo' => asset("assets/images/games_images/header (1).jpg"),
        //         'description' => 'Realmwalker: New Dawn',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Realmwalker: New Dawn',
        //         'meta_description' => 'Realmwalker: New Dawn',
        //         'meta_keywords' => 'Realmwalker: New Dawn',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 17,
        //         'name' => 'RuneScape 3 Gold',
        //         'slug' => 'runescape-3-gold',
        //         'logo' => asset("assets/images/games_images/images (3).jpg"),
        //         'description' => 'RuneScape 3 Gold',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'RuneScape 3 Gold',
        //         'meta_description' => 'RuneScape 3 Gold',
        //         'meta_keywords' => 'RuneScape 3 Gold',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 18,
        //         'name' => 'Lost Ark Gold',
        //         'slug' => 'lost-ark-gold',
        //         'logo' => asset("assets/images/games_images/LA_T4-Gold-Founder-Pack-Key-Art_580x326.jpg"),
        //         'description' => 'Lost Ark Gold',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Lost Ark Gold',
        //         'meta_description' => 'Lost Ark Gold',
        //         'meta_keywords' => 'Lost Ark Gold',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'sort_order' => 19,
        //         'name' => 'Old School RuneScape Gold',
        //         'slug' => 'old-school-runescape-gold',
        //         'logo' => asset("assets/images/games_images/images (4).jpg"),
        //         'description' => 'Old School RuneScape Gold',
        //         'status' => GameStatus::ACTIVE->value,
        //         'meta_title' => 'Old School RuneScape Gold',
        //         'meta_description' => 'Old School RuneScape Gold',
        //         'meta_keywords' => 'Old School RuneScape Gold',
        //         'created_by' => Admin::inRandomOrder()->value('id'),
        //         'created_at' => now(),
        //     ],
        // ];

        $games = [
            [
                'sort_order' => 1,
                'name' => 'EA Sports FC 24 Coins',
                'slug' => 'ea-sports-fc-24-coins',
                'description' => 'EA Sports FC 24 Coins',
                'logo' => asset('assets/images/games_images/fc24.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'EA Sports FC 24 Coins',
                'meta_description' => 'Buy EA Sports FC 24 Coins',
                'meta_keywords' => 'EA Sports FC 24 Coins',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 2,
                'name' => 'World of Warcraft Gold',
                'slug' => 'world-of-warcraft-gold',
                'description' => 'World of Warcraft Gold',
                'logo' => asset('assets/images/games_images/wow.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'World of Warcraft Gold',
                'meta_description' => 'Buy WoW Gold',
                'meta_keywords' => 'World of Warcraft Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 3,
                'name' => 'Old School RuneScape Gold',
                'slug' => 'old-school-runescape-gold',
                'description' => 'Old School RuneScape Gold',
                'logo' => asset('assets/images/games_images/osrs.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'OSRS Gold',
                'meta_description' => 'Buy OSRS Gold',
                'meta_keywords' => 'OSRS Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 4,
                'name' => 'RuneScape 3 Gold',
                'slug' => 'runescape-3-gold',
                'description' => 'RuneScape 3 Gold',
                'logo' => asset('assets/images/games_images/rs3.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'RuneScape 3 Gold',
                'meta_description' => 'Buy RuneScape 3 Gold',
                'meta_keywords' => 'RuneScape 3 Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 5,
                'name' => 'Albion Online Silver',
                'slug' => 'albion-online-silver',
                'description' => 'Albion Online Silver',
                'logo' => asset('assets/images/games_images/albion.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Albion Online Silver',
                'meta_description' => 'Buy Albion Online Silver',
                'meta_keywords' => 'Albion Online Silver',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 6,
                'name' => 'Path of Exile Currency',
                'slug' => 'path-of-exile-currency',
                'description' => 'Path of Exile Currency',
                'logo' => asset('assets/images/games_images/poe.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Path of Exile Currency',
                'meta_description' => 'Buy Path of Exile Currency',
                'meta_keywords' => 'Path of Exile Currency',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 7,
                'name' => 'Lost Ark Gold',
                'slug' => 'lost-ark-gold',
                'description' => 'Lost Ark Gold',
                'logo' => asset('assets/images/games_images/lost-ark.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Lost Ark Gold',
                'meta_description' => 'Buy Lost Ark Gold',
                'meta_keywords' => 'Lost Ark Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 8,
                'name' => 'Black Desert Online Silver',
                'slug' => 'black-desert-online-silver',
                'description' => 'Black Desert Online Silver',
                'logo' => asset('assets/images/games_images/bdo.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'BDO Silver',
                'meta_description' => 'Buy Black Desert Silver',
                'meta_keywords' => 'BDO Silver',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 9,
                'name' => 'New World Coins',
                'slug' => 'new-world-coins',
                'description' => 'New World Coins',
                'logo' => asset('assets/images/games_images/new-world.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'New World Coins',
                'meta_description' => 'Buy New World Coins',
                'meta_keywords' => 'New World Coins',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 10,
                'name' => 'Final Fantasy XIV Gil',
                'slug' => 'final-fantasy-xiv-gil',
                'description' => 'Final Fantasy XIV Gil',
                'logo' => asset('assets/images/games_images/ffxiv.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'FFXIV Gil',
                'meta_description' => 'Buy FFXIV Gil',
                'meta_keywords' => 'FFXIV Gil',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 11,
                'name' => 'GTA Online Money',
                'slug' => 'gta-online-money',
                'description' => 'GTA Online Money',
                'logo' => asset('assets/images/games_images/gta.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'GTA Online Money',
                'meta_description' => 'Buy GTA Online Money',
                'meta_keywords' => 'GTA Online Money',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 12,
                'name' => 'Diablo IV Gold',
                'slug' => 'diablo-iv-gold',
                'description' => 'Diablo IV Gold',
                'logo' => asset('assets/images/games_images/diablo4.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Diablo IV Gold',
                'meta_description' => 'Buy Diablo IV Gold',
                'meta_keywords' => 'Diablo IV Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 13,
                'name' => 'Elder Scrolls Online Gold',
                'slug' => 'elder-scrolls-online-gold',
                'description' => 'Elder Scrolls Online Gold',
                'logo' => asset('assets/images/games_images/eso.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'ESO Gold',
                'meta_description' => 'Buy ESO Gold',
                'meta_keywords' => 'ESO Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 14,
                'name' => 'MapleStory Mesos',
                'slug' => 'maplestory-mesos',
                'description' => 'MapleStory Mesos',
                'logo' => asset('assets/images/games_images/maplestory.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'MapleStory Mesos',
                'meta_description' => 'Buy MapleStory Mesos',
                'meta_keywords' => 'MapleStory Mesos',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 15,
                'name' => 'Warframe Platinum',
                'slug' => 'warframe-platinum',
                'description' => 'Warframe Platinum',
                'logo' => asset('assets/images/games_images/warframe.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Warframe Platinum',
                'meta_description' => 'Buy Warframe Platinum',
                'meta_keywords' => 'Warframe Platinum',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 16,
                'name' => 'Destiny 2 Silver',
                'slug' => 'destiny-2-silver',
                'description' => 'Destiny 2 Silver',
                'logo' => asset('assets/images/games_images/destiny2.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Destiny 2 Silver',
                'meta_description' => 'Buy Destiny 2 Silver',
                'meta_keywords' => 'Destiny 2 Silver',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 17,
                'name' => 'Tower of Fantasy Tanium',
                'slug' => 'tower-of-fantasy-tanium',
                'description' => 'Tower of Fantasy Tanium',
                'logo' => asset('assets/images/games_images/tof.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Tower of Fantasy Tanium',
                'meta_description' => 'Buy Tower of Fantasy Tanium',
                'meta_keywords' => 'Tower of Fantasy Tanium',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 18,
                'name' => 'Guild Wars 2 Gold',
                'slug' => 'guild-wars-2-gold',
                'description' => 'Guild Wars 2 Gold',
                'logo' => asset('assets/images/games_images/gw2.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Guild Wars 2 Gold',
                'meta_description' => 'Buy Guild Wars 2 Gold',
                'meta_keywords' => 'Guild Wars 2 Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 19,
                'name' => 'Blade & Soul Gold',
                'slug' => 'blade-and-soul-gold',
                'description' => 'Blade & Soul Gold',
                'logo' => asset('assets/images/games_images/bns.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Blade & Soul Gold',
                'meta_description' => 'Buy Blade & Soul Gold',
                'meta_keywords' => 'Blade & Soul Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 20,
                'name' => 'Conqueror’s Blade Silver',
                'slug' => 'conquerors-blade-silver',
                'description' => 'Conqueror’s Blade Silver',
                'logo' => asset('assets/images/games_images/conquerors-blade.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Conqueror’s Blade Silver',
                'meta_description' => 'Buy Conqueror’s Blade Silver',
                'meta_keywords' => 'Conqueror’s Blade Silver',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 21,
                'name' => 'Monster Hunter World Zenny',
                'slug' => 'monster-hunter-world-zenny',
                'description' => 'Monster Hunter World Zenny',
                'logo' => asset('assets/images/games_images/mhw.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Monster Hunter World Zenny',
                'meta_description' => 'Buy Monster Hunter World Zenny',
                'meta_keywords' => 'Monster Hunter World Zenny',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 22,
                'name' => 'ARK Survival Evolved Items',
                'slug' => 'ark-survival-evolved-items',
                'description' => 'ARK Survival Evolved Items',
                'logo' => asset('assets/images/games_images/ark.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'ARK Survival Items',
                'meta_description' => 'Buy ARK Survival Evolved Items',
                'meta_keywords' => 'ARK Survival Items',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 23,
                'name' => 'Rust Skins',
                'slug' => 'rust-skins',
                'description' => 'Rust Skins',
                'logo' => asset('assets/images/games_images/rust.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Rust Skins',
                'meta_description' => 'Buy Rust Skins',
                'meta_keywords' => 'Rust Skins',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 24,
                'name' => 'Escape from Tarkov Roubles',
                'slug' => 'escape-from-tarkov-roubles',
                'description' => 'Escape from Tarkov Roubles',
                'logo' => asset('assets/images/games_images/tarkov.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Escape from Tarkov Roubles',
                'meta_description' => 'Buy EFT Roubles',
                'meta_keywords' => 'Escape from Tarkov Roubles',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 25,
                'name' => 'EVE Online ISK',
                'slug' => 'eve-online-isk',
                'description' => 'EVE Online ISK',
                'logo' => asset('assets/images/games_images/eve.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'EVE Online ISK',
                'meta_description' => 'Buy EVE Online ISK',
                'meta_keywords' => 'EVE Online ISK',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 26,
                'name' => 'Roblox Robux',
                'slug' => 'roblox-robux',
                'description' => 'Roblox Robux',
                'logo' => asset('assets/images/games_images/roblox.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Roblox Robux',
                'meta_description' => 'Buy Roblox Robux',
                'meta_keywords' => 'Roblox Robux',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 27,
                'name' => 'Valorant Points',
                'slug' => 'valorant-points',
                'description' => 'Valorant Points',
                'logo' => asset('assets/images/games_images/valorant.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Valorant Points',
                'meta_description' => 'Buy Valorant Points',
                'meta_keywords' => 'Valorant Points',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 28,
                'name' => 'League of Legends RP',
                'slug' => 'league-of-legends-rp',
                'description' => 'League of Legends RP',
                'logo' => asset('assets/images/games_images/lol.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'League of Legends RP',
                'meta_description' => 'Buy League of Legends RP',
                'meta_keywords' => 'League of Legends RP',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 29,
                'name' => 'Dota 2 Items',
                'slug' => 'dota-2-items',
                'description' => 'Dota 2 Items',
                'logo' => asset('assets/images/games_images/dota2.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Dota 2 Items',
                'meta_description' => 'Buy Dota 2 Items',
                'meta_keywords' => 'Dota 2 Items',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 30,
                'name' => 'Counter-Strike 2 Skins',
                'slug' => 'counter-strike-2-skins',
                'description' => 'Counter-Strike 2 Skins',
                'logo' => asset('assets/images/games_images/cs2.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'CS2 Skins',
                'meta_description' => 'Buy CS2 Skins',
                'meta_keywords' => 'CS2 Skins',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 31,
                'name' => 'Apex Legends Coins',
                'slug' => 'apex-legends-coins',
                'description' => 'Apex Legends Coins',
                'logo' => asset('assets/images/games_images/apex.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Apex Legends Coins',
                'meta_description' => 'Buy Apex Legends Coins',
                'meta_keywords' => 'Apex Legends Coins',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 32,
                'name' => 'Fortnite V-Bucks',
                'slug' => 'fortnite-v-bucks',
                'description' => 'Fortnite V-Bucks',
                'logo' => asset('assets/images/games_images/fortnite.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Fortnite V-Bucks',
                'meta_description' => 'Buy Fortnite V-Bucks',
                'meta_keywords' => 'Fortnite V-Bucks',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 33,
                'name' => 'Call of Duty Warzone COD Points',
                'slug' => 'call-of-duty-warzone-cod-points',
                'description' => 'Call of Duty Warzone COD Points',
                'logo' => asset('assets/images/games_images/warzone.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'COD Points',
                'meta_description' => 'Buy Call of Duty COD Points',
                'meta_keywords' => 'COD Points',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 34,
                'name' => 'Honkai Star Rail Stellar Jade',
                'slug' => 'honkai-star-rail-stellar-jade',
                'description' => 'Honkai Star Rail Stellar Jade',
                'logo' => asset('assets/images/games_images/hsr.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Honkai Star Rail Stellar Jade',
                'meta_description' => 'Buy Honkai Star Rail Stellar Jade',
                'meta_keywords' => 'Honkai Star Rail Stellar Jade',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 35,
                'name' => 'Genshin Impact Genesis Crystals',
                'slug' => 'genshin-impact-genesis-crystals',
                'description' => 'Genshin Impact Genesis Crystals',
                'logo' => asset('assets/images/games_images/genshin.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Genshin Impact Genesis Crystals',
                'meta_description' => 'Buy Genshin Impact Genesis Crystals',
                'meta_keywords' => 'Genshin Impact Genesis Crystals',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 36,
                'name' => 'Mobile Legends Diamonds',
                'slug' => 'mobile-legends-diamonds',
                'description' => 'Mobile Legends Diamonds',
                'logo' => asset('assets/images/games_images/mobile-legends.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Mobile Legends Diamonds',
                'meta_description' => 'Buy Mobile Legends Diamonds',
                'meta_keywords' => 'Mobile Legends Diamonds',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 37,
                'name' => 'PUBG Mobile UC',
                'slug' => 'pubg-mobile-uc',
                'description' => 'PUBG Mobile UC',
                'logo' => asset('assets/images/games_images/pubg-mobile.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'PUBG Mobile UC',
                'meta_description' => 'Buy PUBG Mobile UC',
                'meta_keywords' => 'PUBG Mobile UC',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 38,
                'name' => 'Free Fire Diamonds',
                'slug' => 'free-fire-diamonds',
                'description' => 'Free Fire Diamonds',
                'logo' => asset('assets/images/games_images/free-fire.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Free Fire Diamonds',
                'meta_description' => 'Buy Free Fire Diamonds',
                'meta_keywords' => 'Free Fire Diamonds',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 39,
                'name' => 'Clash of Clans Gems',
                'slug' => 'clash-of-clans-gems',
                'description' => 'Clash of Clans Gems',
                'logo' => asset('assets/images/games_images/clash-of-clans.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Clash of Clans Gems',
                'meta_description' => 'Buy Clash of Clans Gems',
                'meta_keywords' => 'Clash of Clans Gems',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 40,
                'name' => 'Clash Royale Gems',
                'slug' => 'clash-royale-gems',
                'description' => 'Clash Royale Gems',
                'logo' => asset('assets/images/games_images/clash-royale.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Clash Royale Gems',
                'meta_description' => 'Buy Clash Royale Gems',
                'meta_keywords' => 'Clash Royale Gems',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 41,
                'name' => 'FIFA Mobile Coins',
                'slug' => 'fifa-mobile-coins',
                'description' => 'FIFA Mobile Coins',
                'logo' => asset('assets/images/games_images/fifa-mobile.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'FIFA Mobile Coins',
                'meta_description' => 'Buy FIFA Mobile Coins',
                'meta_keywords' => 'FIFA Mobile Coins',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 42,
                'name' => 'NBA 2K24 VC',
                'slug' => 'nba-2k24-vc',
                'description' => 'NBA 2K24 VC',
                'logo' => asset('assets/images/games_images/nba2k24.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'NBA 2K24 VC',
                'meta_description' => 'Buy NBA 2K24 VC',
                'meta_keywords' => 'NBA 2K24 VC',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 43,
                'name' => 'Red Dead Online Gold Bars',
                'slug' => 'red-dead-online-gold-bars',
                'description' => 'Red Dead Online Gold Bars',
                'logo' => asset('assets/images/games_images/rdo.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Red Dead Online Gold Bars',
                'meta_description' => 'Buy Red Dead Online Gold Bars',
                'meta_keywords' => 'Red Dead Online Gold Bars',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 44,
                'name' => 'Sea of Thieves Gold',
                'slug' => 'sea-of-thieves-gold',
                'description' => 'Sea of Thieves Gold',
                'logo' => asset('assets/images/games_images/sea-of-thieves.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Sea of Thieves Gold',
                'meta_description' => 'Buy Sea of Thieves Gold',
                'meta_keywords' => 'Sea of Thieves Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 45,
                'name' => 'Palworld Coins',
                'slug' => 'palworld-coins',
                'description' => 'Palworld Coins',
                'logo' => asset('assets/images/games_images/palworld.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Palworld Coins',
                'meta_description' => 'Buy Palworld Coins',
                'meta_keywords' => 'Palworld Coins',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 46,
                'name' => 'Helldivers 2 Credits',
                'slug' => 'helldivers-2-credits',
                'description' => 'Helldivers 2 Credits',
                'logo' => asset('assets/images/games_images/helldivers2.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Helldivers 2 Credits',
                'meta_description' => 'Buy Helldivers 2 Credits',
                'meta_keywords' => 'Helldivers 2 Credits',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 47,
                'name' => 'Dragon Nest Gold',
                'slug' => 'dragon-nest-gold',
                'description' => 'Dragon Nest Gold',
                'logo' => asset('assets/images/games_images/dragon-nest.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Dragon Nest Gold',
                'meta_description' => 'Buy Dragon Nest Gold',
                'meta_keywords' => 'Dragon Nest Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 48,
                'name' => 'Perfect World Gold',
                'slug' => 'perfect-world-gold',
                'description' => 'Perfect World Gold',
                'logo' => asset('assets/images/games_images/perfect-world.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Perfect World Gold',
                'meta_description' => 'Buy Perfect World Gold',
                'meta_keywords' => 'Perfect World Gold',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 49,
                'name' => 'MU Online Zen',
                'slug' => 'mu-online-zen',
                'description' => 'MU Online Zen',
                'logo' => asset('assets/images/games_images/mu-online.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'MU Online Zen',
                'meta_description' => 'Buy MU Online Zen',
                'meta_keywords' => 'MU Online Zen',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sort_order' => 50,
                'name' => 'Lineage 2 Adena',
                'slug' => 'lineage-2-adena',
                'description' => 'Lineage 2 Adena',
                'logo' => asset('assets/images/games_images/lineage2.jpg'),
                'status' => GameStatus::ACTIVE->value,
                'meta_title' => 'Lineage 2 Adena',
                'meta_description' => 'Buy Lineage 2 Adena',
                'meta_keywords' => 'Lineage 2 Adena',
                'created_by' => Admin::inRandomOrder()->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];


        Game::insert($games);
    }
}
